# Generated by Django 4.2 on 2023-04-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0004_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
