# Generated by Django 4.2 on 2023-05-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
