# Generated by Django 4.2 on 2023-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0009_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
